context:
  version: "0.7.0"

package:
  name: jupyter-ai-tools
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-ai-tools/jupyter_ai_tools-${{ version }}.tar.gz
  sha256: d23c5b60722c4b68909141ab5bd792bbca3843203dd193f59c1a40c077a213b1

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5
  run:
    - python >=${{ python_min }}
    - jupyter_server >=1.6,<3
    - jupyter_ydoc >=3.0.0
    - jupyterlab-ai-commands >=0.4.0
    - jupyterlab-commands-toolkit
    - pycrdt

tests:
  - python:
      imports:
        - jupyter_ai_tools
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-ai-tools
  summary: "A suite of tools for AI agents in Jupyter"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyter-ai-tools

extra:
  recipe-maintainers:
    - jtpio
    - dlqqq
    - andrii-i
